import type { ElementPaletteItem } from './test-plan-modeller-graph.service';

export const utilityPaletteItems: readonly ElementPaletteItem[] = [
  {
    elementId: null,
    label: 'Resize viewport',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'RESIZE_VIEWPORT',
  },
  {
    elementId: null,
    label: 'Coordinate click',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'COORDINATE_CLICK',
  },
  {
    elementId: null,
    label: 'Explicit wait',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'EXPLICIT_WAIT',
  },
  {
    elementId: null,
    label: 'Local storage search',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'LOCAL_STORAGE_SEARCH',
  },
  {
    elementId: null,
    label: 'Session storage search',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'SESSION_STORAGE_SEARCH',
  },
  {
    elementId: null,
    label: 'Cookie search',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'COOKIE_SEARCH',
  },
  {
    elementId: null,
    label: 'Downloaded file check',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'DOWNLOADED_FILE_CHECK',
  },
  {
    elementId: null,
    label: 'Document text check',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'DOWNLOADED_DOCUMENT_TEXT_CHECK',
  },
  {
    elementId: null,
    label: 'Move viewport',
    locatorString: '',
    locatorType: '-',
    type: 'UTILITY',
    defaultActionType: 'VIEWPORT_MOVE',
  },
];
